#!/usr/bin/env bash
# Function to display subdomain information

func () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]; then
  sub_doms=("www" "lb-01" "web-01" "web-02")
  for sub_dom in "${sub_doms[@]}"; do
    func "$1" "$sub_dom"
  done
  elif [ "$#" == 2 ]; then
    func "$1" "$2"
fi
