#!/bin/env bash
# Redirect to another page
sudo apt-get update
sudo apt-get install -y nginx

sudo bash -c 'cat > /etc/nginx/sites-available/redirect_me' <<EOF
server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/
sudo rm /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx reload
