#!/usr/bin/env bash
# Configure custom 404 page
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
SERVER_CONFIG=\
"server {
	listen 80 default_server;
	error_page 404 /404.html;
  location = /404.html {
    root /var/www/html;
    internal;
  }
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	rewrite ^/redirect_me https://www.google.com/;
	location / {
		try_files \$uri \$uri/ =404;
	}
}"

bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

if ! service nginx status > /dev/null; then
	service nginx start
else
	service nginx restart
fi
