#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 402643-web-01 52.204.67.182:80 check\n\tserver 402643-web-02 18.209.180.1:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
