#!/usr/bin/env bash
# Bash file that creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
delete_file() {
  rm /var/run/myscript.pid
  exit
}
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; delete_file' SIGTERM
trap 'echo "I hate the kill command"; delete_file' SIGQUIT
echo $$ > /var/run/myscript.pid
while :; do echo "To infinity and beyond"; sleep 2; done
