#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i=1
while [ $i -le 20 ]; do
    if [ $i == 4 ]
    then
      echo -e $i "\nbad luck from China"
    elif [ $i = 9 ]
    then
      echo -e $i "\nbad luck from Japan"
    elif [ $i = 17 ]
    then
      echo -e $i "\nbad luck from Italy"
    else
      echo $i
    fi
    i=$(( i + 1))
done
