#!/usr/bin/env bash
# Run Nginx as Nginx
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
mkdir -p /run/nginx
chown -R nginx:nginx /var/www/html /run/nginx
service nginx start
